Scrum 28 budget creation
Pokket-Budget-Management/Pokket pull request #11
Opened 2024-04-28 17:02 UTC by nhuy703

Added CreateBudget form
Configured Firebase FireStore and Authentication

2024-04-28 22:29 UTC, hthm00 requested changes
Missing package even after npm i. Did you install the package correctly inside frontend/ folder?
<img width="687" alt="Screenshot 2024-04-28 at 3 26 37 PM" src="https://github.com/Pokket-Budget-Management/Pokket/assets/38261965/6fbd40e1-efb6-4e4c-a8bb-2683e84538eb">

2024-04-28 22:29 UTC, hthm00 commented on frontend/package.json
No firebase module in this?

2024-04-29 01:17 UTC, nhuy703 commented on frontend/package.json
Oh you need to run these in the root folder. Sorry I forgot to include that ):
npm install --save firebase

2024-04-29 01:20 UTC, hthm00 commented on frontend/package.json
Can you install in the frontend/ because this is where our code is. If you notice, there is a different packpage.json for the backend/. So no need to install at root level

2024-04-29 06:40 UTC, hthm00 approved these changes
Excellent work!

2024-04-30 16:25 UTC, merged